=== Kamil10p/XML/1zadanie.dtd
<!ELEMENT plik (informacje_o_pliku,przychodnia)> 
<!ELEMENT informacje_o_pliku (opis_zawartosci,autor+,data_modyfikacji,osoba_modyfikujaca)> 
<!ELEMENT opis_zawartosci (#PCDATA)> 
<!ELEMENT autor (#PCDATA)> 
<!ELEMENT data_modyfikacji (#PCDATA)> 
<!ELEMENT osoba_modyfikujaca (#PCDATA)> 
<!ELEMENT przychodnia (wizyty,karty_pacjentow)

 
<!ELEMENT wizyty (wizyta*)> 
<!ELEMENT wizyta (data_wizyty,objawy,rozpoznanie,zalecenia,data_kolejnej_wizyty?)> 
<!ATTLIST wizyta numer ID #REQUIRED> 
<!ATTLIST wizyta numer_id_pacjenta IDREF #REQUIRED> 
<!ELEMENT data_wizyty (#PCDATA)> 
<!ELEMENT objawy (#PCDATA)> 
<!ELEMENT rozpoznanie (#PCDATA)> 
<!ELEMENT zalecenia (#PCDATA)> 
<!ELEMENT data_kolejnej_wizyty (#PCDATA)> 
 
 
<!ELEMENT karty_pacjentow (karta_pacjenta*)> 
<!ELEMENT karta_pacjenta (numer_ubezpieczenia,dane_personalne,wiek,numer_tel,adres,alergie,przebyte_choroby,szczepienia,grupa_krwi,przyjmowane_obecnie_leki)> 
<!ATTLIST karta_pacjenta numer_id ID #REQUIRED> 
<!ELEMENT numer_ubezpieczenia(#PCDATA)> 
<!ELEMENT dane_personalne(imie,nazwisko)>
<!ATTLIST dane_personalne plec (M|K) #REQUIRED> 
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)> 
<!ELEMENT wiek (#PCDATA)>
<!ELEMENT numer_tel(#PCDATA)>


<!ELEMENT adres (kraj,miasto,kod_pocztowy,ulica,nr_mieszkania)> 
<!ELEMENT kraj (#PCDATA)> 
<!ELEMENT miasto (#PCDATA)> 
<!ELEMENT kod_pocztowy (#PCDATA)> 
<!ELEMENT ulica (#PCDATA)> 
<!ELEMENT nr_mieszkania (#PCDATA)> 
<!ELEMENT alergie (#PCDATA)>
<!ELEMENT przebyte_choroby (#PCDATA)> 
<!ELEMENT szczepienia (#PCDATA)> 
<!ELEMENT grupa_krwi (#PCDATA)> 
<!ELEMENT przyjmowane_obecnie_leki (#PCDATA)>

=== Kamil10p/XML/1zadanie.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plik SYSTEM "1zadanie.dtd">
<?xml-stylesheet href="1zadanie.css"?>

<plik>
<informacje_o_pliku>
	<opis_zawartosci>System przychodni</opis_zawartosci>
	<autor>Dawid Pytka</autor>
	<autor>Kamil Piątkowski</autor>
	<data_modyfikacji>09.10.2018</data_modyfikacji>
	<osoba_modyfikujaca>Kamil Piątkowski</osoba_modyfikujaca>
	
</informacje_o_pliku>
<przychodnia>
<wizyty>
<wizyta numer="1" numer_id_pacjenta="p1">
			<data_wizyty>10-12-18</data_wizyty>
			<objawy>Kaszel</objawy>
			<rozpoznanie>Grypa</rozpoznanie>
			<zalecenia></zalecenia>
</wizyta>
<wizyta numer="2" numer_id_pacjenta="p2">
			<data_wizyty>10-12-18</data_wizyty>
			<objawy>Kaszel</objawy>
			<rozpoznanie>Grypa</rozpoznanie>
			<zalecenia>Rutinoskorbin</zalecenia>
			<data_kolejnej_wizyty>20-12-18</data_kolejnej_wizyty>
</wizyta>
</wizyty>
<karty_pacjentow>
<karta_pacjenta numer_id="p1">
	<dane_personalne plec="M">
		<imie>Jan</imie>
		<nazwisko>Nowak</nazwisko>
		<wiek>40</wiek>
		<numer_tel>7894566123</numer_tel>
		<numer_ubezpieczenia>123456</numer_ubezpieczenia>
	</dane_personalne>
    <adres>
        <kraj>Polska</kraj>
        <miasto>Łódź</miasto>
        <kod_pocztowy>95-200</kod_pocztowy>
        <ulica>Piotrkowska</ulica>
		<nr_mieszkania>32</nr_mieszkania>
    </adres>	
		<alergie>Brak</alergie>
		<przebyte_choroby>odra</przebyte_choroby>
		<szczepienia>świnka, rzerzączka</szczepienia>
		<grupa_krwi>A</grupa_krwi>
		<przyjmowane_obecnie_leki>Brak</przyjmowane_obecnie_leki>
        
</karta_pacjenta>
<karta_pacjenta numer_id="p2">
	<dane_personalne plec="M">
		<imie>Jan</imie>
		<nazwisko>Nowak</nazwisko>
		<wiek>40</wiek>
		<numer_tel>7894566123</numer_tel>
		<numer_ubezpieczenia>123456</numer_ubezpieczenia>
	</dane_personalne>
    <adres>
        <kraj>Polska</kraj>
        <miasto>Łódź</miasto>
        <kod_pocztowy>95-200</kod_pocztowy>
        <ulica>Piotrkowska</ulica>
		<nr_mieszkania>32</nr_mieszkania>
    </adres>	
		<alergie>Brak</alergie>
		<przebyte_choroby>odra</przebyte_choroby>
		<szczepienia>świnka, rzerzączka</szczepienia>
		<grupa_krwi>A</grupa_krwi>
		<przyjmowane_obecnie_leki>Brak</przyjmowane_obecnie_leki>
        
</karta_pacjenta>
</karty_pacjentow>
</przychodnia>
</plik>
