=== Kamil10p/XML/2zadanie.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.piatpyt.org/2zadanie" 
xmlns:nasza="http://www.piatpyt.org/2zadanie" 
elementFormDefault="unqualified">

<xs:element name="addresses">
<xs:complexType>
<xs:sequence>
<xs:element name="plik">
<xs:complexType> 
<xs:sequence>
<xs:element name="informacje_o_pliku">
<xs:complexType>
<xs:sequence>
<xs:element name="opis_zawartości" type="xs:string"/>
<xs:element name="autor" type="xs:string"/>
<xs:element name="autor1" type="xs:string"/>
<xs:element name="data_modyfikacji" type="xs:date"/>
<xs:element name="osoba_modyfikująca" type="xs:string"/>

</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="przychodnia">
<xs:complexType>
<xs:sequence>
<xs:element name="wizyty">
<xs:complexType>
<xs:sequence>
<xs:element name="wizyta" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="data_wizyty" type="nasza:typ_data"/>
<xs:element name="objawy" type="nasza:krotki_tekst"/>
<xs:element name="rozpoznanie" type="nasza:krotki_tekst"/>
<xs:element name="zalecenia" type="nasza:krotki_tekst"/>


<xs:element name="data_kolejnej_wizyty" >
<xs:simpleType>
<xs:union memberTypes="xs:string nasza:typ_data"/>
</xs:simpleType>
</xs:element>



</xs:sequence>
<xs:attribute name="numer" type="xs:ID" use="required"/>
<xs:attribute name="numer_id_pacjenta" type="xs:IDREF" use="required"/>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType> 
</xs:element>


<xs:element name="baza_danych">
<xs:complexType>
<xs:sequence>
<xs:element name="karty_pacjentów">
<xs:complexType>
<xs:sequence>
<xs:element name="karta_pacjenta" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>


<xs:element name="numer_ubezpieczenia" type="xs:positiveInteger"/>

<xs:element name="dane_personalne">
<xs:complexType>
<xs:sequence>
<xs:element name="nazwisko" type="xs:string"/>
<xs:element name="imię" type="xs:string"/>
</xs:sequence>
<xs:attribute name="płeć" type="xs:string" use="required"/>
</xs:complexType>
</xs:element>

<xs:element name="wiek" type="xs:positiveInteger"/>
<xs:element name="numer_tel" type="nasza:typNr_tel"/>

<xs:element name="adres">
<xs:complexType>
<xs:sequence>
<xs:element name="kraj" type="xs:string"/>
<xs:element name="miasto" type="xs:string"/>
<xs:element name="kod_pocztowy" type="nasza:typKod_pocztowy"/>
<xs:element name="ulica" type="xs:string"/>
<xs:element name="nr_mieszkania" type="xs:positiveInteger"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:group ref="nasza:dodatkowe_informacje"/>



</xs:sequence>
<xs:attribute name="numer_id" type="xs:ID" use="required"/>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
<xs:key name="Idpacjenta">
<xs:selector xpath="./karty_pacjentów/karta_pacjenta"/>
<xs:field xpath="@numer_id"/>
</xs:key>
<xs:keyref name="Idrefpacjenta" refer="nasza:Idpacjenta">
<xs:selector xpath="./wizyty/wizyta"/>
<xs:field xpath="@numer_id_pacjenta"/>
</xs:keyref>
<xs:key name="Idwizyty">
<xs:selector xpath="./wizyty/wizyta"/>
<xs:field xpath="@numer"/>
</xs:key>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>



<xs:simpleType name="typNr_tel">
<xs:restriction base="xs:integer">
<xs:pattern value="\d{9}"/>
</xs:restriction>
</xs:simpleType>


<xs:simpleType name="typKod_pocztowy" >
<xs:restriction base="xs:string">
<xs:pattern value="\d{2}-\d{3}"/>
</xs:restriction>
</xs:simpleType>




<xs:simpleType name="typ_data">
<xs:restriction base="xs:date">
<xs:minInclusive value="1939-01-01"/>
<xs:maxInclusive value="2028-01-01"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="krotki_tekst">
<xs:restriction base="xs:string">
<xs:minLength value="1"/>
<xs:maxLength value="99"/>
</xs:restriction>
</xs:simpleType>

<xs:group name="dodatkowe_informacje">
<xs:sequence>
<xs:element name="alergie" type="xs:string"/>
<xs:element name="przebyte_choroby" type="xs:string"/>
<xs:element name="szczepienia" type="xs:string"/>
<xs:element name="grupa_krwi" type="xs:string"/>
<xs:element name="przyjmowane_obecnie_leki" type="xs:string"/>
</xs:sequence>
</xs:group>
</xs:schema>

=== Kamil10p/XML/2zadanie.xml
<?xml version="1.0" encoding="UTF-8"?>
<plik
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="2zadanie.xsd">
<informacje_o_pliku>
	<opis_zawartości>SYSTEM PRZYCHODNI</opis_zawartości>
	<autor>Dawid Pytka</autor>
	<autor1>Kamil Piątkowski</autor1>
	<data_modyfikacji>2018-10-10</data_modyfikacji>
	<osoba_modyfikująca>Kamil Piątkowski</osoba_modyfikująca>
	
</informacje_o_pliku>
<przychodnia>
<wizyty>
<wizyta numer="1" numer_id_pacjenta="1">
			<data_wizyty>2018-10-01</data_wizyty>
			<objawy>gorączka,katar,osłabienie</objawy>
			<rozpoznanie>grypa</rozpoznanie>
			<zalecenia>witamina C, zwolnienie lekarskie z pracy,ambrosol</zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="1" numer_id_pacjenta="2">
			<data_wizyty>2018-10-01</data_wizyty>
			<objawy>ból w prawy oku, osłabione widzenie</objawy>
			<rozpoznanie>jęczmień pod okiem</rozpoznanie>
			<zalecenia>okłady z ziela świetlika 3 razy dziennie</zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="3" numer_id_pacjenta="3">
			<data_wizyty>2018-10-01</data_wizyty>
			<objawy>ból ucha, wysoka gorączka</objawy>
			<rozpoznanie>czyrak prawego ucha</rozpoznanie>
			<zalecenia>okłady ichtiolowe, antybiotyk flukloksacyklina 2 razy dziennie po 1 tabletce</zalecenia>
			<data_kolejnej_wizyty>2018-10-20</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="4" numer_id_pacjenta="4">
			<data_wizyty>2018-10-02</data_wizyty>
			<objawy>duszność, sinica, przyśpieszony i spłycony oddech, apatia</objawy>
			<rozpoznanie>gruźlica prosówkowa</rozpoznanie>
			<zalecenia>Pyrazynamid doustnie 2 tabletki dziennie po jedzeniu, dużo odpoczynku</zalecenia>
			<data_kolejnej_wizyty>2018-11-04</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="5" numer_id_pacjenta="5">
			<data_wizyty>2018-10-02</data_wizyty>
			<objawy>swędzenie skóry głowy, poruszanie się czegoś po włosach</objawy>
			<rozpoznanie>wszy</rozpoznanie>
			<zalecenia>szampon Seboradin Med 2 razy dziennie </zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="6" numer_id_pacjenta="6">
			<data_wizyty>2018-10-03</data_wizyty>
			<objawy>ostry ból gardła, gorączka, powiększone migdałki</objawy>
			<rozpoznanie>angina</rozpoznanie>
			<zalecenia>Augmentin dwa razy dziennie po 1 tabletce </zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="7" numer_id_pacjenta="2">
			<data_wizyty>2018-10-15</data_wizyty>
			<objawy>nienaturalny kształt kości piszczelowej, ból przy próbie poruszania nogą</objawy>
			<rozpoznanie>złamanie kości piszczelowej</rozpoznanie>
			<zalecenia>gips przez 3 tygodnie, leki przeciwbólowe </zalecenia>
			<data_kolejnej_wizyty>2018-11-07</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="8" numer_id_pacjenta="4">
			<data_wizyty>2018-10-16</data_wizyty>
			<objawy>wysypka skórna o charakterze pęcherzykowatym, uporczywy świąd, nadmierna potliwość</objawy>
			<rozpoznanie>potnica</rozpoznanie>
			<zalecenia>testy alergiczne </zalecenia>
			<data_kolejnej_wizyty>2018-11-16</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="9" numer_id_pacjenta="6">
			<data_wizyty>2018-10-16</data_wizyty>
			<objawy>pieczenie paznokci</objawy>
			<rozpoznanie>grzybica paznokci</rozpoznanie>
			<zalecenia>amorolfina miejscowo 3 razy dziennie </zalecenia>
			<data_kolejnej_wizyty>2018-10-23</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="10" numer_id_pacjenta="1">
			<data_wizyty>2018-10-18</data_wizyty>
			<objawy>duszność, kołatanie serca</objawy>
			<rozpoznanie>nadciśnienie</rozpoznanie>
			<zalecenia> aldosteron raz dziennie 1 tabletka, zmiana stylu życia m.in rzucenie palenia papierosów</zalecenia>
			<data_kolejnej_wizyty>2018-11-18</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="11" numer_id_pacjenta="3">
			<data_wizyty>2018-10-19</data_wizyty>
			<objawy>ostry ból w nadbrzuszu, zaparcie</objawy>
			<rozpoznanie>zapalenie wyrostka robaczkowego</rozpoznanie>
			<zalecenia>operacja w szpitalu </zalecenia>
			<data_kolejnej_wizyty>2018-10-26</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="12" numer_id_pacjenta="5">
			<data_wizyty>2018-10-19</data_wizyty>
			<objawy>częste oddawanie moczu</objawy>
			<rozpoznanie>zakażenie układu moczowego</rozpoznanie>
			<zalecenia>antybiotyk Alaks 1 tabletka raz dziennie</zalecenia>
			<data_kolejnej_wizyty>2018-10-26</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="13" numer_id_pacjenta="3">
			<data_wizyty>2018-10-20</data_wizyty>
			<objawy>zdiagnozowany dnia 01-10-2018 czyrak prawego ucha</objawy>
			<rozpoznanie>czyrak prawego ucha</rozpoznanie>
			<zalecenia>kontynuowanie stosowanie okładów ichtiolowych</zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="14" numer_id_pacjenta="5">
			<data_wizyty>2018-10-25</data_wizyty>
			<objawy>rumień na prawej nodze,ból stawów, wysypka skórna, sztywność karku</objawy>
			<rozpoznanie>borelioza</rozpoznanie>
			<zalecenia>antybiotyk Boreliozor przez 4 tyg, 3 tabletki dziennie</zalecenia>
			<data_kolejnej_wizyty>2018-11-25</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="15" numer_id_pacjenta="6">
			<data_wizyty>2018-10-25</data_wizyty>
			<objawy>drżenie rąk, częste biegunki, bezsenność</objawy>
			<rozpoznanie>naczynność tarczycy</rozpoznanie>
			<zalecenia>badanie poziomu TSH we krwi</zalecenia>
			<data_kolejnej_wizyty>2018-11-03</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="16" numer_id_pacjenta="1">
			<data_wizyty>2018-10-25</data_wizyty>
			<objawy>podwyższony poziom glukozy we krwi</objawy>
			<rozpoznanie>cukrzyca</rozpoznanie>
			<zalecenia>zastrzyki z insuliną raz dziennie</zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="17" numer_id_pacjenta="2">
			<data_wizyty>2018-10-25</data_wizyty>
			<objawy>opuchnięte oczy, światłowstręt, przekrwienie spojówkowe</objawy>
			<rozpoznanie>zapalenie spojówek</rozpoznanie>
			<zalecenia>przestrzegać zasad higieny, często myć dłonie, nie pocierać oczu, stosować zimne okłady</zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="18" numer_id_pacjenta="3">
			<data_wizyty>2018-10-26</data_wizyty>
			<objawy>dreszcze, niepokój, zwiotczenie mięśni, bardzo silny ból głowy</objawy>
			<rozpoznanie>udar cieplny</rozpoznanie>
			<zalecenia>zapewniono dostęp do chłodnego powietrza, zastosowano okłady, podano płyny dożylnie</zalecenia>
			<data_kolejnej_wizyty>2018-11-03</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="19" numer_id_pacjenta="4">
			<data_wizyty>2018-10-27</data_wizyty>
			<objawy>krew i limfa wyciekające z prawej dłoni</objawy>
			<rozpoznanie>rana cięta dłoni</rozpoznanie>
			<zalecenia>założenie szwów</zalecenia>
			<data_kolejnej_wizyty>2018-11-07</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="20" numer_id_pacjenta="6">
			<data_wizyty>2018-10-27</data_wizyty>
			<objawy>opuchnięte nogi, ból </objawy>
			<rozpoznanie>zapalenie żył</rozpoznanie>
			<zalecenia>Apiksaban dożylnie dwa razy dziennie</zalecenia>
			<data_kolejnej_wizyty>2018-11-09</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="21" numer_id_pacjenta="3">
			<data_wizyty>2018-11-04</data_wizyty>
			<objawy>ból pleców i kręgosłupa</objawy>
			<rozpoznanie>reumatyzm</rozpoznanie>
			<zalecenia>ćwiczenia podnoszące sprawność fizyczną, pobyt w sanatorium</zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="22" numer_id_pacjenta="2">
			<data_wizyty>2018-11-04</data_wizyty>
			<objawy>silny ból ucha, upośledzenie słuchu</objawy>
			<rozpoznanie>ostre zapalenie ucha środkowego</rozpoznanie>
			<zalecenia>skierowanie do szpitala na zabieg nacięcie błony bębenkowej</zalecenia>
			<data_kolejnej_wizyty>2018-10-26</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="23" numer_id_pacjenta="1">
			<data_wizyty>2018-11-10</data_wizyty>
			<objawy>szmery w płucach, osłabienie, silny suchy kaszel</objawy>
			<rozpoznanie>bakteryjne zapalenie płuc</rozpoznanie>
			<zalecenia>odpoczynek, Sarabin 2 tabletki dziennie (rano i wieczorem)</zalecenia>
			<data_kolejnej_wizyty>2018-11-14</data_kolejnej_wizyty>
</wizyta>
<wizyta numer="24" numer_id_pacjenta="7">
			<data_wizyty>2018-11-10</data_wizyty>
			<objawy>wymioty, silny ból brzucha, jadłowstręt,biegunka</objawy>
			<rozpoznanie>zatrucie pokarmowe</rozpoznanie>
			<zalecenia>uzupełnianie płynów,węgiel aktywny 1 tabletka 3 razy dziennie </zalecenia>
			<data_kolejnej_wizyty>brak</data_kolejnej_wizyty>
</wizyta>

</wizyty>
<baza_danych>
<karty_pacjentów>
<karta_pacjenta numer_id="1">
	<numer_ubezpieczenia>122456</numer_ubezpieczenia>
	<dane_personalne płeć="M">
		<nazwisko>Nowak</nazwisko>
		<imię>Jan</imię>
	</dane_personalne>
	<wiek>40</wiek>
	<numer_tel>789456123</numer_tel>
    <adres>
        <kraj>Polska</kraj>
        <miasto>Łódź</miasto>
        <kod_pocztowy>95-200</kod_pocztowy>
        <ulica>Piotrkowska</ulica>
		<nr_mieszkania>32</nr_mieszkania>
    </adres>	
		<alergie>brak</alergie>
		<przebyte_choroby>odra</przebyte_choroby>
		<szczepienia>świnka, rzerzączka</szczepienia>
		<grupa_krwi>A</grupa_krwi>
		<przyjmowane_obecnie_leki>Accuzide</przyjmowane_obecnie_leki>
        
</karta_pacjenta>
<karta_pacjenta numer_id="2">
	<numer_ubezpieczenia>133456</numer_ubezpieczenia>
	<dane_personalne płeć="M">
		<nazwisko>Kowalski</nazwisko>
		<imię>Piotr</imię>
	</dane_personalne>
	<wiek>23</wiek>
	<numer_tel>785661223</numer_tel>
    <adres>
        <kraj>Polska</kraj>
        <miasto>Łódź</miasto>
        <kod_pocztowy>95-200</kod_pocztowy>
        <ulica>Piotrkowska</ulica>
		<nr_mieszkania>56</nr_mieszkania>
    </adres>	
		<alergie>brak</alergie>
		<przebyte_choroby>odra</przebyte_choroby>
		<szczepienia>świnka, rzerzączka</szczepienia>
		<grupa_krwi>A Rh-</grupa_krwi>
		<przyjmowane_obecnie_leki>Brak</przyjmowane_obecnie_leki>
        
</karta_pacjenta>
<karta_pacjenta numer_id="3">
	<numer_ubezpieczenia>435676</numer_ubezpieczenia>
	<dane_personalne płeć="K">
